### ISSUE TITLE
password authentication failed for user "root"

### ISSUE THREAD

**Issue by m0rd0r64** [vierbergenlars/bareos_exporter#2]
Hi vierbergenlars, when i run: **bareos_exporter -dsn "postgres://bareos@blahblah@127.0.0.1/bareos?parseTime=true"**, the command return this error: password authentication failed for user "root". Can you help me?

thanks!!

**Comment by vierbergenlars** [comment]
Sorry, I totally missed your issue. For some reason I wasn't notified.

> `postgres://bareos@blahblah@127.0.0.1/bareos?parseTime=true`

This is not a valid connection string.

You can look at the documentation of libpq to see how connection strings are specified for postgresql: https://pkg.go.dev/github.com/lib/pq#ParseURL

In this case, it would be `postgres://bareos:blahblah@127.0.0.1/bareos` or `postgres://host=127.0.0.1 user=bareos password=blahblah dbname=bareos`, whichever has your preference.

**Comment by m0rd0r64** [comment]
Now works!! Thank you

Il 20/10/2020 10:27, Lars Vierbergen ha scritto:
